### ISSUE TITLE
Référence supplémentaire : chaine YouTube "system crafters" 

### ISSUE THREAD

**Issue by vincent-picaud** [frederic-santos/formation-orgmode-2021#1]
Bonjour,

Merci pour cette source d'information !

Je voulais juste mentionner aussi la chaine "system crafters" que je trouve absolument super.
Elle contient des vidéos sur Emacs et aussi Org-mode
https://www.youtube.com/results?search_query=org+mode+system+crafters
Peut-être est-ce un lien à rajouter dans les références (sauf erreur de ma part il n'est pas dans la liste)

-- Vincent

**Comment by frederic-santos** [comment]
Salut Vincent,

Merci pour la suggestion ! J'ai ajouté ça dans le commit 443fa1d.

À bientôt !

**Comment by vincent-picaud** [comment]
Super, c'est une chaine que je regarde en ce moment et j'apprends plein de choses :)
Merci,
A+
